In [10]:
import pandas as pd

In [11]:
data=pd.read_csv(r"c:\Users\ROHIT MAURYA\Downloads\reviews_dataset.csv")

In [12]:
data

     review_id                                        review_text sentiment
0            1    Standard packaging, exactly what was described.   Neutral
1            2  This product exceeded my expectations in every...  Positive
2            3   This packaging is reasonably fine for the price.   Neutral
3            4        Disliked the delivery, would not buy again.  Negative
4            5  The packaging performs badly, not worth what I...  Negative
..         ...                                                ...       ...
610        611        Poor delivery, stopped working within days.  Negative
611        612  Very unhappy with the delivery, cannot recomme...  Negative
612        613  Nothing remarkable about the purchase, it's okay.   Neutral
613        614        The item is top notch, couldn't be happier.  Positive
614        615  The order is above expectation, really happy w...  Positive

[615 rows x 3 columns]

In [13]:
data.isnull().sum()

review_id      0
review_text    0
sentiment      0
dtype: int64

In [14]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [15]:
ps = PorterStemmer()
import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'\W', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    cleaned_words = []
    for word in text.split():
        if word not in stopwords.words('english'):
            stemmed = ps.stem(word)
            cleaned_words.append(stemmed)
    return " ".join(cleaned_words)

In [16]:
data['cleaned_review']=data['review_text'].apply(clean_text)
data

,review_id,review_text,sentiment,cleaned_review
0,1,"Standard packaging, exactly what was described.",Neutral,standard packag exactli describ
1,2,This product exceeded my expectations in every...,Positive,product exceed expect everi way
2,3,This packaging is reasonably fine for the price.,Neutral,packag reason fine price
3,4,"Disliked the delivery, would not buy again.",Negative,dislik deliveri would buy
4,5,"The packaging performs badly, not worth what I...",Negative,packag perform badli worth paid
...,...,...,...,...
610,611,"Poor delivery, stopped working within days.",Negative,poor deliveri stop work within day
611,612,"Very unhappy with the delivery, cannot recomme...",Negative,unhappi deliveri cannot recommend
612,613,"Nothing remarkable about the purchase, it's okay.",Neutral,noth remark purchas okay
613,614,"The item is top notch, couldn't be happier.",Positive,item top notch happier
614,615,"The order is above expectation, really happy w...",Positive,order expect realli happi

In [17]:
print(data[['review_text', 'cleaned_review']].head())

                                         review_text  \
0    Standard packaging, exactly what was described.
1  This product exceeded my expectations in every...
2   This packaging is reasonably fine for the price.
3        Disliked the delivery, would not buy again.
4  The packaging performs badly, not worth what I...

                    cleaned_review
0  standard packag exactli describ
1  product exceed expect everi way
2         packag reason fine price
3        dislik deliveri would buy
4  packag perform badli worth paid

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['cleaned_review'])
Y = data['sentiment'].map({'Negative': 0, 'Neutral': 1, 'Positive': 2})
X, Y

(<Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 2505 stored elements and shape (615, 143)>,
 0      1
 1      2
 2      1
 3      0
 4      0
       ..
 610    0
 611    0
 612    1
 613    2
 614    2
 Name: sentiment, Length: 615, dtype: int64)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,data['sentiment'],test_size=0.2,random_state=42)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (492, 143)
Testing data: (123, 143)

In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred)

['Negative' 'Neutral' 'Neutral' 'Negative' 'Positive' 'Positive'
 'Negative' 'Neutral' 'Positive' 'Neutral' 'Positive' 'Negative'
 'Positive' 'Positive' 'Neutral' 'Neutral' 'Neutral' 'Negative' 'Neutral'
 'Neutral' 'Negative' 'Negative' 'Neutral' 'Neutral' 'Neutral' 'Positive'
 'Neutral' 'Negative' 'Positive' 'Negative' 'Negative' 'Neutral'
 'Negative' 'Positive' 'Positive' 'Positive' 'Positive' 'Neutral'
 'Neutral' 'Neutral' 'Positive' 'Positive' 'Neutral' 'Neutral' 'Neutral'
 'Negative' 'Positive' 'Neutral' 'Neutral' 'Negative' 'Positive'
 'Positive' 'Neutral' 'Negative' 'Neutral' 'Neutral' 'Positive' 'Neutral'
 'Positive' 'Positive' 'Positive' 'Neutral' 'Positive' 'Positive'
 'Neutral' 'Negative' 'Neutral' 'Neutral' 'Negative' 'Positive' 'Neutral'
 'Negative' 'Positive' 'Negative' 'Negative' 'Neutral' 'Positive'
 'Positive' 'Positive' 'Negative' 'Positive' 'Positive' 'Negative'
 'Negative' 'Negative' 'Neutral' 'Positive' 'Positive' 'Negative'
 'Positive' 'Neutral' 'Positive' 'Positive' 'Negative' 'Negative'
 'Negative' 'Positive' 'Negative' 'Positive' 'Positive' 'Positive'
 'Negative' 'Neutral' 'Negative' 'Negative' 'Negative' 'Positive'
 'Negative' 'Positive' 'Negative' 'Negative' 'Neutral' 'Positive'
 'Negative' 'Neutral' 'Neutral' 'Positive' 'Positive' 'Positive' 'Neutral'
 'Neutral' 'Neutral' 'Positive']

In [21]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.991869918699187

In [22]:
review = input("Enter your experience/review: ")


cleaned_review = clean_text(review)


review_tfidf = vectorizer.transform([cleaned_review])

print("Predicted Sentiment:", model.predict(review_tfidf)[0])

Predicted Sentiment: Negative